Feature/mc 15 vue3 migration
mandziukGIT/monte-cinema pull request #16
Opened 2022-04-25 08:38 UTC by mandziukGIT

2022-04-25 13:40 UTC, szymonlicau requested changes

2022-04-25 13:40 UTC, szymonlicau commented on src/components/movies/MovieCard.vue
> +  props: ['movie'],
You can have the props done in the same way here too (with the `type` and `default` options) 💡

2022-04-25 13:40 UTC, szymonlicau commented on src/components/movies/MovieCard.vue
> +    const { movie } = toRefs(props);
I'm not sure but I don't think we need to make it a ref 🤔
Any particular reason you made this one a ref?

2022-04-25 13:40 UTC, szymonlicau commented on src/components/register/FinalStep.vue
> +  },
Why not go all the way and move everything into the setup? 🚀

2022-04-25 17:20 UTC, mandziukGIT commented on src/components/register/FinalStep.vue
> +  },
My aim was to just try it out but I will also move rest to setup 🔥

2022-04-25 17:26 UTC, mandziukGIT commented on src/components/movies/MovieCard.vue
> +    const { movie } = toRefs(props);
I guess this time the only reason was my lack of knowledge. You are right 👌

2022-04-26 08:01 UTC, szymonlicau approved these changes
Nice usage of composition API!
Also nice to see some composables :heart:

2022-05-24 09:36 UTC, merged